### ISSUE TITLE
Prevent from creating statue on regions where player is not allowed to build

### ISSUE THREAD

**Issue by homerek111** [SkyTechBytes/PlayerStatueBuilder#12]
I have creative server with plots (plugin: PlotSquared)
I would like to allow creating statues only on player's plots where he can build - as i tested it players can create their statues everywhere...

Is it possible to prevent them from doing so? And allow it only on plots where they have build perms

**Comment by SkyTechBytes** [comment]
Right now the plugin supports WorldGuard protection (https://github.com/SkyTechBytes/PlayerStatueBuilder/blob/master/src/com/skytechbytes/playerstatuebuilder/support/WorldGuardWrapper.java)-- I'll look into how to support PlotSquared protections as well.

**Comment by homerek111** [comment]
> Right now the plugin supports WorldGuard protection (https://github.com/SkyTechBytes/PlayerStatueBuilder/blob/master/src/com/skytechbytes/playerstatuebuilder/support/WorldGuardWrapper.java ) -- I'll look into how to support PlotSquared protections as well.

Yeah… please try to add PlotSquared support - I would be really greatful :))

**Comment by homerek111** [comment]
> Right now the plugin supports WorldGuard protection (https://github.com/SkyTechBytes/PlayerStatueBuilder/blob/master/src/com/skytechbytes/playerstatuebuilder/support/WorldGuardWrapper.java ) -- I'll look into how to support PlotSquared protections as well.

And how did it go??? Is it possible to add support for plotsquared?

**Comment by SkyTechBytes** [comment]
I've been working on it but I'm only just now realizing PlotSquared is a premium resource and so I can't really test out my changes with the plugin. I'll probably push some changes soon but I can't make any promises at the moment.

**Comment by homerek111** [comment]
> I've been working on it but I'm only just now realizing PlotSquared is a premium resource and so I can't really test out my changes with the plugin. I'll probably push some changes soon but I can't make any promises at the moment.

I can test it for you - just let me know when it will be ready :) 

I hope it is possible to manage doing it until Friday - my server’s new season starts that day and I would love to keep your plugin for my players

**Comment by SkyTechBytes** [comment]
Okay try this: https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.15

**Comment by homerek111** [comment]
> Okay try this: https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.15

I does not work :/
1. created a statue on plot that is not mine (from tester account) and it allowed me to do it
2. also created a statue between plots (on the road) and it also allowed me to do it

![obraz](https://github.com/SkyTechBytes/PlayerStatueBuilder/assets/93496464/fb5df844-9fdb-46b9-a53f-9e15c1869336)

Log console:
[09:32:08 INFO]: [PlayerStatueBuilderX] Checking permissions
[09:32:08 INFO]: [PlayerStatueBuilderX] Building is OK | Location{world=CraftWorld{name=dzialka_default},x=-50.0,y=162.0,z=114.0,pitch=0.0,yaw=0.0}/Location{world=CraftWorld{name=dzialka_default},x=-33.0,y=195.0,z=123.0,pitch=0.0,yaw=0.0}
[09:32:08 INFO]: [PlayerStatueBuilderX] WorldGuard can build: true
[09:32:08 INFO]: [PlayerStatueBuilderX] Trying to remove items...
[09:32:08 INFO]: [PlayerStatueBuilderX] Creating Structure...
[09:32:08 INFO]: [PlayerStatueBuilderX] Statue Created

My tester account's permissions from your plugin:
![obraz](https://github.com/SkyTechBytes/PlayerStatueBuilder/assets/93496464/4f93844f-fdff-4c81-961f-9c2face5f035)

**Comment by homerek111** [comment]
> Okay try this: https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.15

did you find a solution?

**Comment by SkyTechBytes** [comment]
The plugin likely did not detect the plotsquared plugin. Check the logs at the beginning. If it says PlotSquared not detected, the plugin will not respect permissions. When you create a statue, if PlotSquared is detected, it should say "PlotSquared can build: true/false". Try this version which will print out an error trace if the plugin is not detected: https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.15 (v1.15.**1**)

**Comment by homerek111** [comment]
> The plugin likely did not detect the plotsquared plugin. Check the logs at the beginning. If it says PlotSquared not detected, the plugin will not respect permissions. When you create a statue, if PlotSquared is detected, it should say "PlotSquared can build: true/false". Try this version which will print out an error trace if the plugin is not detected: https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.15 (v1.15.**1**)

Ye... i think there is some plotsquared detection issue... "PlotSquared not detected"

START LOG:
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Enabling PlayerStatueBuilderX v1.15
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Config.yml found, loading!
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Worldguard detected!
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Vault detected!
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] PlotSquared not detected. The plugin MUST detect PlotSquared if you want the plugin to respect plot squared protections.
[05:51:00] [Server thread/WARN]: java.lang.ClassCastException: class com.plotsquared.bukkit.BukkitPlatform cannot be cast to class com.plotsquared.core.PlotSquared (com.plotsquared.bukkit.BukkitPlatform and com.plotsquared.core.PlotSquared are in unnamed module of loader 'plotsquared-bukkit-7.3.1-SNAPSHOT.jar' @38d92e21)
[05:51:00] [Server thread/WARN]: 	at PlayerStatueBuilderXv1.15.1-SkyTechBytes.jar//com.skytechbytes.playerstatuebuilder.support.PlotSquaredWrapper.<init>(PlotSquaredWrapper.java:18)
[05:51:00] [Server thread/WARN]: 	at PlayerStatueBuilderXv1.15.1-SkyTechBytes.jar//com.skytechbytes.playerstatuebuilder.PlayerStatueBuilder.onEnable(PlayerStatueBuilder.java:44)
[05:51:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[05:51:00] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[05:51:00] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[05:51:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[05:51:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[05:51:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[05:51:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[05:51:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[05:51:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[05:51:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[05:51:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[05:51:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Loading texture /chainmail_armor.png
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Loading texture /iron_armor.png
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Loading texture /golden_armor.png
[05:51:00] [Server thread/INFO]: [PlayerStatueBuilderX] Loading texture /diamond_armor.png


it still allows making statues in wrong regions:
[06:03:40] [Server thread/INFO]: tester420r issued server command: /statue _homerek
[06:03:40] [Server thread/INFO]: [PlayerStatueBuilderX] Checking permissions
[06:03:40] [Server thread/INFO]: [PlayerStatueBuilderX] Building is OK | Location{world=CraftWorld{name=dzialka_default},x=-201.0,y=137.0,z=118.0,pitch=0.0,yaw=0.0}/Location{world=CraftWorld{name=dzialka_default},x=-184.0,y=170.0,z=127.0,pitch=0.0,yaw=0.0}
[06:03:40] [Server thread/INFO]: [PlayerStatueBuilderX] WorldGuard can build: true
[06:03:40] [Server thread/INFO]: [PlayerStatueBuilderX] Trying to remove items...
[06:03:40] [Server thread/INFO]: [PlayerStatueBuilderX] Creating Structure...
[06:03:40] [Server thread/INFO]: [PlayerStatueBuilderX] Statue Created


Maybe this logs can help you finding a solution :)

**Comment by SkyTechBytes** [comment]
This should fix the casting issue to detect plotsquared (v1.15.**2**): https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.15

**Comment by homerek111** [comment]
it works! good job :)
I think you can release the plugin without the console debug messages :)

Also that would be a nice feature to improve the plugin to allow translation of chat messages in config.yml
![obraz](https://github.com/SkyTechBytes/PlayerStatueBuilder/assets/93496464/70e1b3f3-ffb7-45c0-a755-69b07e9bbe4b)

**Comment by SkyTechBytes** [comment]
Newest release is posted to github and spigot https://github.com/SkyTechBytes/PlayerStatueBuilder/releases ! I'll probably look into enabling translations a bit later.
